# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "AUBOT_AGV"
  limits:
    linear: [0.67, 0.5] # velocity, acceleration
    angular: [0.8, 1.5] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.35 # radius in m
    vicinity: 0.45 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 20.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 300.0 # kg
    moment_of_inertia: 6.0 #kgm^2
    friction_coefficient: 0.3
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.4 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
  actions: []
  finishing_request: "charge" # [park, charge, nothing]
  # use_parking_reservations: True
  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  robots:
    VAGV1:
      responsive_wait: True
      charger: "qr_1012"
      finishing_request: # Optionally define any robot-specific finishing request. Overrides the fleet-wide setting.
          type: "park" # [park, charge, nothing]
          waypoint_name: "qr_1104" # This is a required field if the finishing_request type is "park"
    VAGV2:
      responsive_wait: True
      charger: "qr_1011"
      finishing_request: # Optionally define any robot-specific finishing request. Overrides the fleet-wide setting.
          type: "park" # [park, charge, nothing]
          waypoint_name: "qr_1103" # This is a required field if the finishing_request type is "park"
  robot_state_update_frequency: 10.0 # Hz

fleet_manager:
  mqtt_broker: "localhost"
  mqtt_topic: "aubotagv/2.0.0/AUBOT"
  mqtt_client_id: "ROS2_VAGV"
  mqtt_username: "fms"
  mqtt_password: "Aubot@2025"
  mqtt_qos: 0
  mqtt_retain: false
  mqtt_keepalive: 300


