# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "AUBOT_AGV"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.15 # radius in m
    vicinity: 0.25 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.98 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: False
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
  actions: []
  finishing_request: "nothing" # [park, charge, nothing]
  responsive_wait: True # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  robots:
    VAGV1:
      responsive_wait: True
  robot_state_update_frequency: 10.0 # Hz

fleet_manager:
  mqtt_broker: "localhost"
  mqtt_topic: "aubotagv/2.0.0/AUBOT"
  mqtt_client_id: "ROS2_VAGV1"
  mqtt_username: "fms"
  mqtt_password: "Aubot@2025"
  mqtt_qos: 0
  mqtt_retain: false
  mqtt_keepalive: 300


